// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
    {
        "name": "TextPicture",
        "status": true,
        "description": "Displays text as a picture.",
        "parameters": {}
    },
    {
        "name": "ButtonPicture",
        "status": true,
        "description": "Makes a picture clickable.",
        "parameters": {}
    },
    {
        "name": "Jhonny_RaceHelper",
        "status": true,
        "description": "Helpers para o minigame de Corrida (sem logica de jogo). RNG, clamp, W/S/A/D, logger.",
        "parameters": {
            "EnableDebugLogs": "true"
        }
    }
];
